name: Markdownlint CI
on:
  pull_request:
    branches:
      - main
  push:
    branches-ignore:
      - main
    paths:
      - '**.md'
  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:
  markdownlint:
    name: markdownlint
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: DavidAnson/markdownlint-cli2-action@v19
      continue-on-error: true
      with:
        globs: '**/*.md'
